# Generated by Django 4.2.4 on 2023-08-11 21:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('like_app', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='post_id',
            field=models.ManyToManyField(related_name='likes', to='post_app.post'),
        ),
        migrations.AlterField(
            model_name='like',
            name='user_id',
            field=models.ManyToManyField(related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
