# Generated by Django 4.2.4 on 2023-08-22 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment_app', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user_username',
            field=models.CharField(default=''),
            preserve_default=False,
        ),
    ]
