# Generated by Django 4.2.4 on 2023-08-14 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_picture',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
