# Generated by Django 4.2.4 on 2023-08-23 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0003_alter_post_post_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_picture',
        ),
        migrations.AddField(
            model_name='post',
            name='post_file',
            field=models.FileField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
